services:
  angular:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    ports:
      - '4200:80'
    networks:
      - app-network
  
  nest:
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    ports:
      - "3001:3001"  # Map the host port to the container port
    environment:
      - NODE_ENV=production
    networks:
      - app-network 

networks:
  app-network: 
