name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build Angular app
        run: pnpm nx build frontend --prod

      - name: Run Angular tests
        run: pnpm nx test frontend -- --watch=false --bail

      - name: Build NestJS app
        run: pnpm nx build server

      - name: Run NestJS tests
        run: pnpm nx test server -- --watch=false --bail
